[build]
publish = "dist"
command = "vite build"

[[redirects]]
from = "/pyodide/*"
to = "https://cdn.jsdelivr.net/pyodide/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/assets/*"
[headers.values]
cache-control = '''
    max-age=31536000,
    immutable
    '''
